add_newline = true
prompt_order=[
  "username",
  "hostname",
  "kubernetes",
  "directory",
  "git_branch",
  "git_commit",
  "git_state",
  "git_status",
  "docker_context",
  "package",
  "env_var",
  "cmd_duration",
  "custom",
  "line_break",
  "jobs",
  "character",
]

[username]
disabled = false
show_always = true

[hostname]
disabled = false
ssh_only = false

[character]
disabled = false
symbol = "$"
use_symbol_for_status = false

[directory]
disabled = false

[package]
disabled = false

[kubernetes]
disabled = false
